# Generated by Django 4.2.5 on 2024-10-21 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cadastros", "0009_raca_cadastrado_por"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="raca",
            name="cadastrado_por",
        ),
        migrations.AddField(
            model_name="cachorro",
            name="cadastrado_por",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
